"""Building a training mixture, and proving it is the mixture you think it is.

A decision model is only as good as the population it was trained on, and two
things about that population lie quietly:

**Duplicates.** Weighting a source by repeating its rows is the simplest thing
in the world and it is a trap. A row appears four times, contributes four times
to the gradient, and nothing downstream can tell that the *mixture* is no longer
what the recipe said. Counting rows instead of distinct rows is how that goes
unnoticed for several versions. The fix is not to dedupe harder — it is to stop
expressing source weights as repeated rows at all. A weight belongs to the
trainer's sampler, where it costs nothing and stays reversible; a data file
should contain each record once. `Mixture` therefore emits distinct rows and
hands the weights to whoever consumes them.

**Leaks.** If an evaluation set is generated by the same generator as a training
source, an exact-overlap check on the *input text* passes while the model has
still memorised the task. Comparing inputs is not enough, and neither is
trusting a label someone wrote in a metadata file — verified by hand, one
`source` field claimed `contrastive_authorization` while the rows it named were
byte-identical to the evaluation set it was excluded to protect.
"""

from __future__ import annotations

import hashlib
import json
import random
from collections import Counter
from dataclasses import dataclass, field
from typing import Iterable

__all__ = [
    "record_fingerprint",
    "Mixture",
    "audit",
    "find_overlap",
    "load_jsonl",
    "write_jsonl",
]


def _canonical(value) -> str:
    return json.dumps(value, sort_keys=True, ensure_ascii=False, separators=(",", ":"))


def record_fingerprint(record: dict) -> str:
    """A stable fingerprint of a decision record's *content*.

    Deliberately excludes everything except ``state`` and ``questions``: labels,
    provenance and any bookkeeping a builder wrote into ``_meta`` must not make
    two otherwise identical records look different, because that is exactly how
    a duplicate hides from a dedupe pass.
    """
    payload = _canonical(record.get("state")) + "|" + _canonical(record.get("questions"))
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


@dataclass
class Mixture:
    """Collects named sources and emits one shuffled, deduplicated mixture.

    ``weight`` is recorded, not applied: it is a *sampling* weight for the
    trainer, meaning "this source should contribute ``weight`` times as much
    gradient per row as a source with weight 1". ``build`` deliberately does not
    turn a weight into repeated rows, because that is the operation that makes a
    mixture unauditable.
    """

    seed: int = 0
    _sources: dict[str, list[dict]] = field(default_factory=dict)
    _weights: dict[str, float] = field(default_factory=dict)
    _caps: dict[str, int | None] = field(default_factory=dict)

    def add(
        self,
        name: str,
        records: Iterable[dict],
        weight: float = 1.0,
        cap: int | None = None,
    ) -> "Mixture":
        """Add one source. ``cap`` keeps at most that many of its rows.

        When a cap applies, the source is shuffled with the mixture seed before
        truncating, so the kept rows are a spread rather than whatever the file
        happened to start with — a corpus sorted by class would otherwise put
        its cap entirely into the first class.
        """
        if name in self._sources:
            raise ValueError("source %r added twice; merge it before adding" % (name,))
        if weight <= 0:
            raise ValueError("weight for %r must be > 0, got %r" % (name, weight))
        if cap is not None and cap < 1:
            raise ValueError("cap for %r must be >= 1, got %r" % (name, cap))
        rows = [dict(r) for r in records]
        for r in rows:
            missing = [k for k in ("state", "questions") if k not in r]
            if missing:
                raise ValueError("record from %r lacks %s" % (name, "/".join(missing)))
        self._sources[name] = rows
        self._weights[name] = float(weight)
        self._caps[name] = cap
        return self

    def build(self):
        """Return ``(rows, report)``.

        ``rows`` hold each distinct record exactly once, shuffled with the
        mixture seed, every one tagged with ``_meta.source``. ``report`` is the
        recipe as executed: per-source counts before and after the cap, how many
        rows each source dropped as internally duplicated, and the weights the
        trainer is expected to honour. Raises if two *sources* produce the same
        record, since that means the recipe's shares cannot both be true.
        """
        rng = random.Random(self.seed)
        out: list[dict] = []
        report_sources: dict[str, dict] = {}

        for name, rows in self._sources.items():
            shuffled = list(rows)
            rng.shuffle(shuffled)

            seen: set[str] = set()
            kept: list[dict] = []
            internal_dupes = 0
            for row in shuffled:
                fp = record_fingerprint(row)
                if fp in seen:
                    internal_dupes += 1
                    continue
                seen.add(fp)
                kept.append(row)

            cap = self._caps[name]
            capped = kept[:cap] if cap is not None else kept
            for row in capped:
                row = dict(row)
                meta = dict(row.get("_meta") or {})
                meta["source"] = name
                row["_meta"] = meta
                out.append(row)

            report_sources[name] = {
                "inputRows": len(rows),
                "distinctRows": len(kept),
                "internalDuplicates": internal_dupes,
                "cap": cap,
                "emitted": len(capped),
                "weight": self._weights[name],
            }

        rng.shuffle(out)

        by_source = Counter((r.get("_meta") or {}).get("source") for r in out)
        cross = {fp for fp, n in Counter(record_fingerprint(r) for r in out).items() if n > 1}
        if cross:
            owners = sorted({r["_meta"]["source"] for r in out if record_fingerprint(r) in cross})
            raise ValueError(
                "%d records are produced by more than one source (%s); the "
                "source shares in this recipe cannot all be true" % (len(cross), ", ".join(owners))
            )

        report = {
            "seed": self.seed,
            "rows": len(out),
            "uniqueRows": len(out),
            "sources": report_sources,
            "emittedPerSource": dict(by_source),
            "weights": dict(self._weights),
        }
        return out, report


def audit(rows: list[dict]) -> dict:
    """Count rows, distinct rows and duplicates, attributing every duplicate.

    Run this on any file you did not build with `Mixture` — a hand-written
    concatenation, a file from an older version, a corpus someone handed you. It
    reports rather than raises, because it is also how you find out how bad the
    problem is before deciding what to do.
    """
    counts = Counter(record_fingerprint(r) for r in rows)
    owners: dict[str, set[str]] = {}
    for r in rows:
        fp = record_fingerprint(r)
        if counts[fp] > 1:
            owners.setdefault(fp, set()).add((r.get("_meta") or {}).get("source", "<none>"))
    duplicated_sources = sorted({s for who in owners.values() for s in who})
    return {
        "rows": len(rows),
        "uniqueRows": len(counts),
        "duplicateRows": sum(c - 1 for c in counts.values() if c > 1),
        "duplicateGroups": sum(1 for c in counts.values() if c > 1),
        "bySource": dict(Counter((r.get("_meta") or {}).get("source", "<none>") for r in rows)),
        "duplicateSources": duplicated_sources,
    }


def find_overlap(train_rows: list[dict], eval_rows: list[dict]) -> int:
    """How many eval records appear in the training rows, by content fingerprint.

    Any value above zero is not a style problem, it is an invalid evaluation:
    the model has seen the item. ``evaluate`` calls this itself rather than
    trusting the caller to remember, because the number it produces for a
    contaminated suite is worse than useless — it is a number someone will quote.
    """
    train = {record_fingerprint(r) for r in train_rows}
    return sum(1 for r in eval_rows if record_fingerprint(r) in train)


def load_jsonl(path) -> list[dict]:
    with open(path, encoding="utf-8") as f:
        return [json.loads(line) for line in f if line.strip()]


def write_jsonl(path, rows: Iterable[dict]) -> int:
    n = 0
    with open(path, "w", encoding="utf-8") as f:
        for row in rows:
            f.write(json.dumps(row, ensure_ascii=False) + "\n")
            n += 1
    return n
